apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgAjBs8Y3M84+EFc2AIxuCoGdIXpdadTdKwpzmUB36kdkE64Q1uaXqYamjcXfIUXCsLYDUBuxRBgBBLIcbcJyODaqimi8rgDxFz8LWWmnbbs9cGEHLAy12BbWBjy9awyerR3nCMKQkFYvwTvLo0sVI/HD4Z7uWevK81WZZ8u4wAQopDnUK/M1DN27zGaIW04AVjYlzdpcjNnXODjJVq6XYNB+oVfDLhryXTYWduDJ2Axg4KeU4iq55luuJYk752jDt8uQxVoWH4bOGkt/CBrTzsLqc0PVB6L8+0K3oHlauOTtuzrPRmXhhOgJ1NsWmOwXRFbjdBoeVuiparhyEVoJEstBl/kuHIHKEzuHOekY/nlg9KWfBdnemYj8axXYrJlzCqshq0MUcqE5eg4a3uewCGmztsXZtOzqevHjIP0kkAGDK/yqcvhggayxoE71pDnrpUDzwTJH7zJ+VCTQz6kX4Ohhk0SHLQxFNn4emgPTbluiWS0+uB3u83rHfYmCVf2lx/UJRCD7TXSlhqLh8EpupgKFqKVnts2AD7Fy14PBHyvR280Wpox9jxCp7KpW1fAoKSbJ9Zw7ApWACEc6ejqjdFyHrEY4JXSzD7sozwVHXC+4YP1PFs1bvny37QRgsnSM7andvknKgd26uRRkOhrwmXCeXmgCWymDipfkXvwdjQPmPdznNEesB9zdhau8Keew18q26VsRBxQEnsQJlv3iJUHpdFuHWWj1FDg8bwJJAyb+v+WQJ29VoY+
    username: AgBHV1GOfoc/o93i2PtPKYrKtbNvzRSsJ5yGadc4R/hA19v8N0dWE0klChn/wS/UeeOmAOYJJdTpzqOTsy+3BPTiyR0gmae0sEXnQ5g0KbgzpH6fFRxn35bQndf4Et3AO1J4bm+r5eiN+qzhC4/Oq0HcqKhmf0SugdrmSGPlYdoFbyPFsRe3+CMCP/dTbrElZP95+ut+xcSkmfjK9A/tTPmD7LufG6zs3Ob1TZt7zJsFUXHgr8Q+Z1sP1gBsIyr8z/FJOcMKCAPtgVJcXDBLqmFsbSdxd8rsGQ9ZFJUrVSH9lDJ23ZnSQNuelKAQhDXjZ3/E2rrwZNZ2B7XbQDHaS/72Pyd14+vwb5+FD9OUF1A1E5cv9r/J5XoZPWG/A+afbUExd1moC0WQAweC/Sr25ys1OjPa/3q8xWHqs7HV1LOorGJWWSyrOkt0Ae+0kKzTuwldb1vznes0jXMB1Abj3de8pzAR0ujzex58dfSLD8kCcq7Afyz7xtvWwXsrornWtRuMm0tLYsQFvQz3HVvnY9R3V1mYocNmtJbN2UUTzPWyOAyAPPulbkFE3lNI+Lqd+RGjCpxxkElNbmkkWk7wR/Rx3pGYvlAA6vYkU4Xby/02jiSdNHOSMjDwuCs6B89DomTQFEicgAX8OH6lQGv8YYnhXMsugtwnKvJbcA+gkeGnTQey1Y2zEv+INPv2GH9OjOXB5wSVcrSEQU4=
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

